### ISSUE TITLE
Book Space

### ISSUE THREAD

**Issue by hunterowens** [hackforla/ndoch-2017#1]

**Comment by matikin9** [comment]
Ideas:
* Cross Campus DTLA
* General Assembly DTLA

**Comment by hunterowens** [comment]
*  crashspace?

**Comment by matikin9** [comment]
Waiting for carla to confirm whether we can use CCF's space.

**Comment by matikin9** [comment]
datascience.com in culver city

**Comment by lhyman** [comment]
Do we have an update on CCF space availability?

**Comment by carlacasilli** [comment]
Hey all, questions out to the right people at CCF about use of the JPCC: should know more by Thursday 9/7, when the coordinator for the space returns.

**Comment by carlacasilli** [comment]
Hey all, we're good to go. Still working out a few logistics, but SCDC is happy to host the event at the Joan Palevsky Center and cover the lunches and drinks, too. The address for the event is 281 South Figueroa St Suite 100.

**Comment by hunterowens** [comment]
Awesome. I think we should list CCF as primary sponsor for the event?

**Comment by carlacasilli** [comment]
Nice idea. Let me chat with John about whether it's listed as CCF or SCDC, since it's coming from that budget.

**Comment by hunterowens** [comment]
I'm good with either. Anyways, closing this issue as we have a space.

**Comment by lhyman** [comment]
@hunterowens @carlacasilli will we also have the networking happy hour at CCF? If not, do we have another venue in mind?

**Comment by carlacasilli** [comment]
Wish we could say yes to this but can't host any alcohol at the JPCC, so the short answer is no to a networking happy hour in this location.
