### ISSUE TITLE
Sponsorships 

### ISSUE THREAD

**Issue by hunterowens** [hackforla/ndoch-2017#3]

**Comment by matikin9** [comment]
Ideas:
* ESRI

**Comment by vykster** [comment]
I'll take lead on this.  We'll need a brief one pager, a budget, and then to reach out with a few asks. I'll have this all done by EOD Tuesday.

**Comment by matikin9** [comment]
@vykster lemme know if you need the new branding/logo!

**Comment by hunterowens** [comment]
CCF/SCDC will be the be lead sponsor. @carlacasilli to confirm which name to use. 

Potential ESRI, Data Science inc (esp for follow up event)

**Comment by AnthonyRollins** [comment]
@matikin9 @hunterowens @vykster do we have sponsors for the upcoming event?

**Comment by vykster** [comment]
@anthonyrollins, only CCF for this event.
