### ISSUE TITLE
Event Page

### ISSUE THREAD

**Issue by matikin9** [hackforla/ndoch-2017#7]

**Comment by matikin9** [comment]
Eventbrite

**Comment by lhyman** [comment]
Does HfLA have an Eventbrite account? I can get started on this page.

**Comment by matikin9** [comment]
@lhyman i don't believe so.  that would be great if you could start on that. 👍 👍 👍

**Comment by hunterowens** [comment]
@lhyman Let me know when you have a draft eventbrite page up and if you need any copy/details to add to it.

**Comment by lhyman** [comment]
https://www.eventbrite.com/e/national-day-of-civic-hacking-la-tickets-37705667667 

Here's a stub. I'll post the password in Slack. @hunterowens location is biggest need. Feedback on copy also welcome. I can pad it out once we know more about speakers, program, etc.

**Comment by hunterowens** [comment]
@lhyman Location is confirmed, see #1 for more details to add. 

Additionally, speakers from UCLA, KPCC and the LATimes are booked

**Comment by lhyman** [comment]
@hunterowens Done. Let me know if it's ready to go public. 

Will this be back-to-back talks? Workshops? Hands-on or not? Should we encourage people to bring laptops or not?

**Comment by lhyman** [comment]
Done. https://www.eventbrite.com/e/national-day-of-civic-hacking-la-tickets-37705667667
