### ISSUE TITLE
Topic Area

### ISSUE THREAD

**Issue by hunterowens** [hackforla/ndoch-2017#8]
Pick a topic and focus area

*maybe* education

**Comment by hunterowens** [comment]
SCDC Focus Areas: Health, Immigration, Housing, Education 

deadline friday

**Comment by hunterowens** [comment]
@vykster @matikin9 @carlacasilli @lhyman

**Comment by matikin9** [comment]
Immigration and Housing are already getting a lot of attention in LA these days, which makes me lean towards focusing on Education.  Looks like the SCDC site already has info on this focus area: http://scdc.shift3sandbox.com/taxonomy/interest/education/

**Comment by vykster** [comment]
What I mentioned on the call --

-- | Education | Transportation | Housing
---------|-----------|-----------------|-----------
Lots of available datasets (5+) |Yes | Yes | Yes / Partial 
Commonly adopted data standards |No | Partial (GTFS | No 
Existing partnerships  |CCF | No | Maybe 
Potential partnerships |LAUSD, EdDataZone, 826LA | Metro, Big Blue, Ferhan Peers | Skid Row Housing Trust others 
Community outcomes we want to influence | Data publication by school system | ? | Data Standard, etc 
New or pending policy changes | New LAUSD data portal coming || Measure HHH / H accountability

**Comment by carlacasilli** [comment]
Education seems like a ripe topic; I'm currently investigating some possible LAERI content for the SCDC site.  Yesterday Emily F. noted that some of the edu datasets are restricted use, not sure what, if any, role that plays in your dataset list, @vykster.

**Comment by hunterowens** [comment]
I've updated @vykster's chart. Still love education

**Comment by hunterowens** [comment]
Education it is. Closing.
